/* Regenerate web/data.js — the QQQ history bundled into the web app so it shows a signal
 * on open. Re-run after updating the project's data/ folder:   node web/build_data.js   */
const fs = require('fs'), p = require('path');
const S = require('./strategy.js');
const dir = p.join(__dirname, '..', 'data');
const files = fs.readdirSync(dir)
  .filter(function (f) { return f.indexOf('QQQ ') === 0 || f.indexOf('QQQ(') === 0; })
  .map(function (f) { return { name: f, text: fs.readFileSync(p.join(dir, f), 'utf8') }; });
const rows = S.mergeFiles(files);
const csv = S.rowsToCSV(rows);
fs.writeFileSync(p.join(__dirname, 'data.js'),
  '/* Bundled QQQ daily OHLCV (merged from data/), so the page shows a signal on open.\n' +
  '   Generated by web/build_data.js — re-run after updating data/. Do not hand-edit. */\n' +
  'window.QQQ_DATA=' + JSON.stringify(csv) + ';\n');
console.log('wrote web/data.js: ' + rows.length + ' rows, ' + rows[0].date + ' … ' + rows[rows.length - 1].date);
